// generated by Fast Light User Interface Designer (fluid) version 1.0100

#ifndef DiagramFrame_h
#define DiagramFrame_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Chart.H>

class CDiagramFrame {
public:
  CDiagramFrame();
  Fl_Window *wndDiagram;
  Fl_Chart *chartDiagram;
  void show();
  void hide();
};
#endif
