// generated by Fast Light User Interface Designer (fluid) version 1.0400

#include "StatusMessage.h"
static int x; 

CStatusMessage::CStatusMessage() {
  { wndStatus = new Fl_Double_Window(298, 100, "Status");
    wndStatus->user_data((void*)(this));
    { sldProgress = new Fl_Slider(5, 70, 285, 25);
      sldProgress->type(3);
    } // Fl_Slider* sldProgress
    { outMessage = new Fl_Output(5, 5, 285, 55);
      outMessage->color(FL_SELECTION_COLOR);
      outMessage->labelsize(12);
      outMessage->textsize(12);
      outMessage->align(Fl_Align(FL_ALIGN_CENTER));
    } // Fl_Output* outMessage
    wndStatus->set_non_modal();
    wndStatus->end();
    wndStatus->resizable(wndStatus);
  } // Fl_Double_Window* wndStatus
}

void CStatusMessage::show() {
  wndStatus->show();
  wndStatus->redraw();
  wndStatus->make_current();
}

void CStatusMessage::hide() {
  wndStatus->hide();
}

void CStatusMessage::setProgressMax(int maxValue) {
  sldProgress->maximum(maxValue);
}

void CStatusMessage::setProgress(int pos) {
  sldProgress->value(pos);
  wndStatus->make_current();
  sldProgress->redraw();
}

void CStatusMessage::setMessage(char* msg) {
  outMessage->value(msg);
  outMessage->redraw();
  wndStatus->make_current();
}
