// generated by Fast Light User Interface Designer (fluid) version 1.0100

#include "StatusMessage.h"
static int x;

CStatusMessage::CStatusMessage() {
  Fl_Window* w;
  { Fl_Window* o = wndStatus = new Fl_Window(298, 100, "Status");
    w = o;
    o->user_data((void*)(this));
    { Fl_Slider* o = sldProgress = new Fl_Slider(5, 70, 285, 25);
      o->type(3);
    }
    { Fl_Output* o = outMessage = new Fl_Output(5, 5, 285, 55);
      o->color(15);
      o->labelsize(12);
      o->textsize(12);
      o->align(FL_ALIGN_CENTER);
    }
    o->set_non_modal();
    o->end();
    o->resizable(o);
  }
}

void CStatusMessage::show() {
  wndStatus->show();
wndStatus->redraw();
wndStatus->make_current();
}

void CStatusMessage::hide() {
  wndStatus->hide();
}

void CStatusMessage::setProgressMax(int maxValue) {
  sldProgress->maximum(maxValue);
}

void CStatusMessage::setProgress(int pos) {
  sldProgress->value(pos);
wndStatus->make_current();
sldProgress->redraw();
}

void CStatusMessage::setMessage(char* msg) {
  outMessage->value(msg);
outMessage->redraw();
wndStatus->make_current();
}
