if (WIN32)
    if (CMAKE_BUILD_TYPE STREQUAL "Debug")
        message("Debug libraries...")
        set(FLTK_INCLUDE_DIR "d:/Libraries/fltk")
        set(FLTK_ABI_INCLUDE_DIR "d:/Libraries/fltk/build-debug")
        set(FLTK_BASE_LIBRARY "d:/Libraries/fltk/build-debug/lib/Debug/fltkd.lib")
        set(FLTK_GL_LIBRARY "d:/Libraries/fltk/build-debug/lib/Debug/fltk_gld.lib")
        set(JPEG_INCLUDE_DIR "d:/Libraries/fltk/jpeg")
        set(JPEG_LIBRARY "d:/Libraries/fltk/build-debug/lib/Debug/fltk_jpegd.lib")
        set(PNG_INCLUDE_DIR "d:/Libraries/fltk/png")
        set(PNG_LIBRARY "d:/Libraries/fltk/build-debug/lib/Debug/fltk_pngd.lib")
        set(ZLIB_INCLUDE_DIR "d:/Libraries/fltk/zlib")
        set(ZLIB_LIBRARY "d:/Libraries/fltk/build-debug/lib/Debug/fltk_zd.lib")
        set(GLEW_INCLUDE_DIR "d:/Libraries/glew/include")
        set(GLEW_LIBRARY "d:/Libraries/glew/lib/Debug/x64/glew32sd.lib")
        #set(FREETYPE_INCLUDE_DIR
        set(OPENGL_LIBRARY "opengl32")
        set(GLUT_INCLUDE_DIR "D:/Libraries/freeglut/include")
        set(GLUT_LIBRARY "D:/Libraries/freeglut/build-debug/lib/Debug/freeglut_staticd.lib")
        set(GDIPLUS_LIBRARY "gdiplus")
    else()
        message("Release libraries...")
        set(FLTK_INCLUDE_DIR "d:/Libraries/fltk")
        set(FLTK_ABI_INCLUDE_DIR "d:/Libraries/fltk/build-release")
        set(FLTK_BASE_LIBRARY "d:/Libraries/fltk/build-release/lib/Release/fltk.lib")
        set(FLTK_GL_LIBRARY "D:/Libraries/fltk/build-release/lib/Release/fltk_gl.lib")
        set(JPEG_INCLUDE_DIR "d:/Libraries/fltk/jpeg")
        set(JPEG_LIBRARY "d:/Libraries/fltk/build-release/lib/Release/fltk_jpeg.lib")
        set(PNG_INCLUDE_DIR "d:/Libraries/fltk/png")
        set(PNG_LIBRARY "d:/Libraries/fltk/build-release/lib/Release/fltk_png.lib")
        set(ZLIB_INCLUDE_DIR "d:/Libraries/fltk/zlib")
        set(ZLIB_LIBRARY "d:/Libraries/fltk/build-release/lib/Release/fltk_z.lib")
        set(GLEW_INCLUDE_DIR "d:/Libraries/glew/include")
        set(GLEW_LIBRARY "d:/Libraries/glew/lib/Release/x64/glew32s.lib")
        #set(FREETYPE_INCLUDE_DIR
        set(OPENGL_LIBRARY "opengl32")
        set(GLUT_INCLUDE_DIR "D:/Libraries/freeglut/include")
        set(GLUT_LIBRARY "D:/Libraries/freeglut/build-release/lib/Release/freeglut_static.lib")
        set(GDIPLUS_LIBRARY "gdiplus")
    endif()
endif()
