// generated by Fast Light User Interface Designer (fluid) version 1.0009

#include "MainFrame.h"
#include <Mmsystem.h>

CMainFrame::CMainFrame() {
  Fl_Window* w;
  { Fl_Window* o = wndMain = new Fl_Window(494, 469, "Fly");
    w = o;
    o->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(0, 0, 494, 469);
      ivfFlyWidget = new CIvfFlyWidget(0, 0, 494, 469);
      o->end();
    }
    o->end();
    o->resizable(o);
  }
}

void CMainFrame::show() {
  wndMain->show();
ivfFlyWidget->show();

MMRESULT mmResult;
mmResult = joySetCapture(
fl_xid(ivfFlyWidget),
JOYSTICKID1,50,TRUE);
}
