// generated by Fast Light User Interface Designer (fluid) version 1.0009

#ifndef MainFrame_h
#define MainFrame_h
#include <FL/Fl.H>
#include <FL/x.h>
#include <FL/Fl_Window.H>
#include <FL/Fl_Group.H>
#include "IvfFlyWidget.h"

class CMainFrame {
public:
  CMainFrame();
  Fl_Window *wndMain;
  CIvfFlyWidget *ivfFlyWidget;
  void show();
};
#endif
