// generated by Fast Light User Interface Designer (fluid) version 1.0100

#include "DiagramFrame.h"
static int x;

CDiagramFrame::CDiagramFrame() {
  Fl_Window* w;
  { Fl_Window* o = wndDiagram = new Fl_Window(411, 300, "Stress");
    w = o;
    o->user_data((void*)(this));
    chartDiagram = new Fl_Chart(5, 5, 400, 290);
    o->set_non_modal();
    o->end();
    o->resizable(o);
  }
}

void CDiagramFrame::show() {
  wndDiagram->show();
}

void CDiagramFrame::hide() {
  wndDiagram->hide();
}
