// generated by Fast Light User Interface Designer (fluid) version 1.0100

#ifndef StatusMessage_h
#define StatusMessage_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Output.H>

class CStatusMessage {
public:
  CStatusMessage();
  Fl_Window *wndStatus;
  Fl_Slider *sldProgress;
  Fl_Output *outMessage;
  void show();
  void hide();
  void setProgressMax(int maxValue);
  void setProgress(int pos);
  void setMessage(char* msg);
};
#endif
