// generated by Fast Light User Interface Designer (fluid) version 1.0104

#include "RobotWindow.h"

CRobotWindow::CRobotWindow() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = wndMain = new Fl_Double_Window(601, 481);
    w = o;
    o->user_data((void*)(this));
    { CRobotView* o = robotView = new CRobotView(80, 10, 445, 450, "label");
      o->box(FL_FLAT_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_BLACK);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
      Fl_Group::current()->resizable(o);
    }
    o->end();
  }
}

void CRobotWindow::show() {
  wndMain->show();
robotView->show();
}
